export const PUBLIC_DATA_ENCODING_API_KEY = import.meta.env.VITE_PUBLIC_DATA_ENCODING_API_KEY;
export const PUBLIC_DATA_DECODING_API_KEY = import.meta.env.VITE_PUBLIC_DATA_DECODING_API_KEY;
export const NAVER_MAP_CLIENT_ID = import.meta.env.VITE_NAVER_MAP_CLIENT_ID;
export const NAVER_MAP_CLIENT_SECRET = import.meta.env.VITE_NAVER_MAP_CLIENT_SECRET;
